#!/bin/bash

# Copyright © 2014-2016 by madneon
# http://madneon.com

logger "QEMU hook: $1 $2"

MYPATH=`readlink -f "$0"`
MYPATH=`dirname "$MYPATH"`

if [ ! -f $MYPATH/forward-$1 ]; then
	exit 0
fi

forwards=`cat $MYPATH/forward-$1`

for r in $forwards; do
	from_port=`echo $r|cut -f1 -d"-"`
	to_port=`echo $r|cut -f2 -d"-"`
	to_addr=`echo $to_port|cut -f1 -d":"`
	to_port=`echo $to_port|cut -f2 -d":"`
	protocol=`echo $to_port|cut -f2 -d"/"`
	to_port=`echo $to_port|cut -f1 -d"/"`

	if [ "$2" = "start" ]; then
		action=on
	elif [ "$2" = "stopped" ]; then
		action=off
	else
		action=
	fi

	if [ -n "$action" ]; then
		. router-forward $action $from_port $to_addr $to_port $protocol
	fi
done

# madneon 2014-12-16, 2015-04-02, 2016-09-07
