#!/bin/bash

sudo /usr/sbin/locale-gen
sudo update-alternatives --set x-terminal-emulator /usr/bin/tilix.wrapper
sudo update-alternatives --set editor /usr/bin/mcedit
sudo update-alternatives --set pager /usr/bin/most
sudo update-grub
cd /opt/lib/os-deploy/ && git pull && /opt/lib/os-deploy/bin/deploy
