#!/bin/bash

sudo update-alternatives --set x-terminal-emulator /usr/bin/tilix.wrapper
sudo update-alternatives --set editor /usr/bin/mcedit
sudo update-alternatives --set pager /usr/bin/most
sudo update-grub
